rabbitmq:
  image:
    repository: syunkitada/centos7-rabbitmq
    tag: latest
    pullPolicy: Always
  replicas: 3
  user: openstack
  pass: openstackpass
  ro_user: openstackro
  ro_pass: openstackropass
  master: dummy
  vhost_map:
    test:
      policies:
        - ha-two '.*' '{"ha-mode":"exactly","ha-params":2,"ha-sync-mode":"automatic"}'
        - TTL 'notifications.*' '{"message-ttl":600000}' --apply-to queues
    nova:
      policies:
        - ha-two '.*' '{"ha-mode":"exactly","ha-params":2,"ha-sync-mode":"automatic"}'
        - TTL 'notifications.*' '{"message-ttl":600000}' --apply-to queues
    neutron:
      policies:
        - ha-two '.*' '{"ha-mode":"exactly","ha-params":2,"ha-sync-mode":"automatic"}'
        - TTL 'notifications.*' '{"message-ttl":600000}' --apply-to queues
    common:
      policies:
        - ha-two '.*' '{"ha-mode":"exactly","ha-params":2,"ha-sync-mode":"automatic"}'
        - TTL 'notifications.*' '{"message-ttl":600000}' --apply-to queues
