apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: glance
  labels:
    chart: glance
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: glance
    spec:
      containers:
      - name: glance
        # command: ["bash", "-c", "echo 'pre setup' && sleep 3600;"]
        command: [
          "/opt/glance/bin/glance-api",
          "--config-file", "/etc/glance/glance-api.conf",
        ]
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: 9292
        volumeMounts:
          - name: etc-glance
            mountPath: /etc/glance
      - name: glance-api
        # command: ["bash", "-c", "echo 'pre setup' && sleep 3600;"]
        command: [
          "/opt/glance/bin/glance-registry",
          "--config-file", "/etc/glance/glance-registry.conf",
        ]
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: 9191
        volumeMounts:
          - name: etc-glance
            mountPath: /etc/glance
      volumes:
        - name: etc-glance
          configMap:
            name: etc-glance
