apiVersion: v1
kind: Service
metadata:
  name: glance
  labels:
    chart: glance
spec:
  type: ClusterIP
  ports:
    - port: 9191
      targetPort: 9191
      protocol: TCP
      name: glance-registry
    - port: 9292
      targetPort: 9292
      protocol: TCP
      name: glance-api
  selector:
    app: glance
