{{- $domain_suffix := print .Release.Namespace ".svc.cluster.local" }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: bin-init-uwsgi
data:
  util.py: |+
{{ tuple "bin/common/_util.py.tpl" . | include "funcs.template" | indent 4 }}
  init.py: |+
{{ tuple "bin/common/_init_service.py.tpl" . | include "funcs.template" | indent 4 }}
  service.py: |+
{{ tuple "bin/common/_uwsgi_service.py.tpl" . | include "funcs.template" | indent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: bin-init-eventlet
data:
  util.py: |+
{{ tuple "bin/common/_util.py.tpl" . | include "funcs.template" | indent 4 }}
  init.py: |+
{{ tuple "bin/common/_init_service.py.tpl" . | include "funcs.template" | indent 4 }}
  service.py: |+
{{ tuple "bin/common/_eventlet_service.py.tpl" . | include "funcs.template" | indent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: bin-init-controller
data:
  util.py: |+
{{ tuple "bin/common/_util.py.tpl" . | include "funcs.template" | indent 4 }}
  init.py: |+
{{ tuple "bin/common/_init_controller.py.tpl" . | include "funcs.template" | indent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: bin-keystone
data:
  bootstrap.sh: |+
{{ tuple "bin/keystone/_bootstrap.sh.tpl" . | include "funcs.template" | indent 4 }}
  dbsync.sh: |+
{{ tuple "bin/keystone/_dbsync.sh.tpl" . | include "funcs.template" | indent 4 | replace "@domain_suffix" $domain_suffix}}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: bin-glance
data:
  bootstrap.sh: |+
{{ tuple "bin/glance/_bootstrap.sh.tpl" . | include "funcs.template" | indent 4 }}
  dbsync.sh: |+
{{ tuple "bin/glance/_dbsync.sh.tpl" . | include "funcs.template" | indent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: bin-neutron
data:
  bootstrap.sh: |+
{{ tuple "bin/neutron/_bootstrap.sh.tpl" . | include "funcs.template" | indent 4 }}
  dbsync.sh: |+
{{ tuple "bin/neutron/_dbsync.sh.tpl" . | include "funcs.template" | indent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: bin-nova
data:
  bootstrap.sh: |+
{{ tuple "bin/nova/_bootstrap.sh.tpl" . | include "funcs.template" | indent 4 }}
  dbsync.sh: |+
{{ tuple "bin/nova/_dbsync.sh.tpl" . | include "funcs.template" | indent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: bin-horizon
data:
  bootstrap.sh: |+
{{ tuple "bin/horizon/_bootstrap.sh.tpl" . | include "funcs.template" | indent 4 }}
