apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-keystone
data:
  keystone.conf: |+
{{ tuple "etc/_keystone.conf.tpl" . | include "funcs.template" | indent 4 }}


---


apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-nginx
data:
  nginx.conf: |+
{{ tuple "etc/_nginx.conf.tpl" . | include "funcs.template" | indent 4 }}


---


apiVersion: v1
kind: ConfigMap
metadata:
  name: bin-keystone
data:
  bootstrap.sh: |+
{{ tuple "bin/keystone/_bootstrap.sh.tpl" . | include "funcs.template" | indent 4 }}
  dbsync.sh: |+
{{ tuple "bin/keystone/_dbsync.sh.tpl" . | include "funcs.template" | indent 4 }}


---


apiVersion: v1
kind: ConfigMap
metadata:
  name: bin-init-uwsgi
data:
  init.py: |+
{{ tuple "bin/_init.py.tpl" . | include "funcs.template" | indent 4 }}
  service.py: |+
{{ tuple "bin/_uwsgi_service.py.tpl" . | include "funcs.template" | indent 4 }}
