apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-common
data:
  adminrc: |+
{{ tuple "etc/common/_adminrc.tpl" . | include "funcs.template" | indent 4 }}
  resolv.conf: |+
{{ tuple "etc/common/_resolv.conf.tpl" . | include "funcs.template" | indent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-nginx
data:
  nginx.conf: |+
{{ tuple "etc/nginx/_nginx.conf.tpl" . | include "funcs.template" | indent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-keystone
data:
  keystone.conf: |+
{{ tuple "etc/keystone/_keystone.conf.tpl" . | include "funcs.template" | indent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-glance
data:
  glance-api.conf: |+
{{ tuple "etc/glance/_glance-api.conf.tpl" . | include "funcs.template" | indent 4 }}
  glance-registry.conf: |+
{{ tuple "etc/glance/_glance-registry.conf.tpl" . | include "funcs.template" | indent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-neutron
data:
  neutron.conf: |+
{{ tuple "etc/neutron/_neutron.conf.tpl" . | include "funcs.template" | indent 4 }}
  ml2_conf.ini: |+
{{ tuple "etc/neutron/_ml2_conf.ini.tpl" . | include "funcs.template" | indent 4 }}
  linuxbridge_agent.ini: |+
{{ tuple "etc/neutron/_linuxbridge_agent.ini.tpl" . | include "funcs.template" | indent 4 }}
  dhcp_agent.ini: |+
{{ tuple "etc/neutron/_dhcp_agent.ini.tpl" . | include "funcs.template" | indent 4 }}
  metadata_agent.ini: |+
{{ tuple "etc/neutron/_metadata_agent.ini.tpl" . | include "funcs.template" | indent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-nova
data:
  nova.conf: |+
{{ tuple "etc/nova/_nova.conf.tpl" . | include "funcs.template" | indent 4 }}
