apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nova-compute
  labels:
    chart: nova
spec:
  template:
    metadata:
      labels:
        app: nova-compute
    spec:
      hostNetwork: true
      containers:
        - name: nova-compute
          command: ["bash", "-c", "echo 'pre setup' && sleep 3600;"]
          # command: ["/mnt/nova/bin/start-compute.sh"]
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true
          volumeMounts:
            - name: etc-resolv-conf
              mountPath: /etc/resolv.conf
              subPath: resolv.conf
            - name: etc-nova
              mountPath: /etc/nova
            - name: bin-nova
              mountPath: /mnt/nova/bin
            - name: lib
              mountPath: /lib/
              readOnly: true
            - name: lib64
              mountPath: /lib64/
              readOnly: true
            - name: usr
              mountPath: /usr/
            - name: var-run-libvirt
              mountPath: /var/run/libvirt
            - name: host
              mountPath: /host
            - name: etc
              mountPath: /etc/machine-id
              subPath: machine-id
            - name: sbin
              mountPath: /sbin/
            - name: etc
              mountPath: /etc/sudoers
              subPath: sudoers
      volumes:
        - name: etc-resolv-conf
          configMap:
            name: etc-resolv-conf
        - name: etc-nova
          configMap:
            name: etc-nova
        - name: bin-nova
          configMap:
            name: bin-nova
            defaultMode: 0755
        - name: lib
          hostPath:
            path: /lib
        - name: lib64
          hostPath:
            path: /lib64
        - name: usr
          hostPath:
            path: /usr
        - name: var-run-libvirt
          hostPath:
            path: /var/run/libvirt
        - name: host
          hostPath:
            path: /
        - name: etc
          hostPath:
            path: /etc
        - name: sbin
          hostPath:
            path: /sbin
