apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitoring-prometheus
spec:
  replicas: 1
  template:
    metadata:
      name: monitoring-prometheus
      labels:
        app: monitoring-prometheus
    spec:
      containers:
        - name: monitoring-prometheus
          image: prom/prometheus:v1.4.0
          args:
            - -config.file=/mnt/etc/prometheus.yml
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /mnt/etc/
            - name: data-volume
              mountPath: /mnt/data/
            - name: secrets-volume
              mountPath: /var/run/secrets
      volumes:
        - name: config-volume
          configMap:
            name: monitoring-prometheus-config
        - name: data-volume
          emptyDir: {}
        - name: secrets-volume
          hostPath:
            path: /var/run/secrets
