apiVersion: v1
kind: ConfigMap
metadata:
  name: keystone-etc
data:
  keystone.conf: |+
{{ tuple "etc/_keystone.conf.tpl" . | include "funcs.template" | indent 4 }}


---


apiVersion: v1
kind: ConfigMap
metadata:
  name: keystone-bin
data:
  init.py: |+
{{ tuple "bin/_init.py.tpl" . | include "funcs.template" | indent 4 }}
  service.py: |+
{{ tuple "bin/_service.py.tpl" . | include "funcs.template" | indent 4 }}
