apiVersion: v1
kind: Service
metadata:
  name: keystone-public
  labels:
    chart: keystone
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: keystone-public
  selector:
    app: keystone-public


---


apiVersion: v1
kind: Service
metadata:
  name: keystone-admin
  labels:
    chart: keystone
spec:
  type: ClusterIP
  ports:
  - port: 35357
    targetPort: 35357
    protocol: TCP
    name: keystone-admin
  selector:
    app: keystone-admin
