apiVersion: v1
kind: Service
metadata:
  name: keystone
  labels:
    chart: keystone
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: public
  - port: 35357
    targetPort: 35357
    protocol: TCP
    name: admin
  selector:
    app: keystone
