#!/bin/bash -xe

echo 'Starting influxdb'

COMMAND="${@:-start}"


function start(){
    echo "Starting influxdb in the background"
    exec /usr/bin/influxd --config /etc/influxdb/influxdb.conf &
    influx -execute "CREATE USER root WITH PASSWORD 'root' WITH ALL PRIVILEGES;"
    influx -execute "CREATE DATABASE k8s;"
    influx -execute "CREATE DATABASE openstack;"
    sed -i 's/auth-enabled =.*/auth-enabled = true/g' /etc/influxdb/influxdb.conf
    sed -i 's/bind-address = "127.0.0.1:8088"/bind-address = "0.0.0.0:8088"/g' /etc/influxdb/influxdb.conf
    sed -i 's/bind-address = "127.0.0.1:8086"/bind-address = "0.0.0.0:8086"/g' /etc/influxdb/influxdb.conf
    pkill influxd

    /usr/bin/influxd --config /etc/influxdb/influxdb.conf
}


$COMMAND
