{{- $influxdb := .Values.influxdb }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitoring-influxdb
  namespace: kube-system
  labels:
    k8s-app: monitoring-influxdb
    version: v4
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: monitoring-influxdb
        kubernetes.io/cluster-service: "true"
        version: v4
      annotations:
        influxdb-configmap: {{ tuple "influxdb-configmap.yaml" . | include "funcs.hash" }}
    spec:
      containers:
        - name: influxdb
          image: {{ $influxdb.image }}
          command: ["/mnt/influxdb/bin/influxdb.sh", "start"]
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 500Mi
          ports:
            - containerPort: 8083
            - containerPort: 8088
          volumeMounts:
            - name: var-lib-influxdb
              mountPath: /var/lib/influxdb
            - name: influxdb-etc
              mountPath: /etc/influxdb
            - name: influxdb-bin
              mountPath: /mnt/influxdb/bin
      volumes:
        - name: var-lib-influxdb
          emptyDir: {}
        - name: influxdb-etc
          configMap:
            name: influxdb-etc
        - name: influxdb-bin
          configMap:
            name: influxdb-bin
            defaultMode: 0755
