apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitoring-prometheus
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  replicas: 1
  template:
    metadata:
      name: monitoring-prometheus
      labels:
        k8s-app: monitoring-prometheus
        kubernetes.io/cluster-service: "true"
      annotations:
        prometheus-configmap: {{ tuple "prometheus-configmap.yaml" . | include "funcs.hash" }}
    spec:
      serviceAccount: heapster
      containers:
        - name: monitoring-prometheus
          image: prom/prometheus:v1.4.0
          args:
            - -config.file=/mnt/etc/prometheus.yml
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /mnt/etc/
            - name: data-volume
              mountPath: /mnt/data/
            - name: secrets-volume
              mountPath: /var/run/secrets
      volumes:
        - name: config-volume
          configMap:
            name: monitoring-prometheus-config
        - name: data-volume
          emptyDir: {}
        - name: secrets-volume
          hostPath:
            path: /var/run/secrets
