apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-prometheus-config
  namespace: kube-system
data:
  prometheus.yml: |
{{ tuple "etc/_prometheus.yml.tpl" . | include "funcs.template" | indent 4 }}
