apiVersion: v1
kind: Service
metadata:
  name: monitoring-prometheus
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: monitoring-prometheus
spec:
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    k8s-app: monitoring-prometheus
