{{- $name := .Release.Name }}

apiVersion: v1
kind: Service
metadata:
  name: "{{ $name }}"
  labels:
    app: "{{ $name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: NodePort
  ports:
    - name: rabbitmq
      port: 5672
      targetPort: 5672
  selector:
    app: {{ .Values.selector }}


---


apiVersion: v1
kind: Service
metadata:
  name: "{{ $name }}-management"
  labels:
    app: "{{ $name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
    - name: rabbitmq-management
      port: 15672
      targetPort: 15672
  selector:
    app: {{ .Values.selector }}
