apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nova-compute
  labels:
    chart: nova
spec:
  template:
    metadata:
      labels:
        app: nova-compute
    spec:
      hostNetwork: true
      containers:
      - name: nova-compute
        lifecycle:
          postStart:
            exec:
              command: [
                "echo", "hello"
              ]
        command: ["bash", "-c", "echo 'pre setup' && sleep 3600;"]
        # command: ["bash", "-c", "python3 /mnt/bin/init-eventlet/init.py"]
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          privileged: true
        volumeMounts:
        - name: etc-nova
          mountPath: /etc/nova
        - name: host
          mountPath: /host/
      volumes:
      - name: etc-nova
        configMap:
          name: etc-nova
      - name: host
        hostPath:
          path: /
