apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: glance-controller
  labels:
    chart: glance
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      name: glance-controller
      labels:
        chart: glance
    spec:
      containers:
      - name: glance-controller
        # command: ["bash", "-c", "echo 'pre setup' && sleep 3600;"]
        command: ["bash", "-c", "python3 /mnt/bin/init-controller/init.py"]
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: etc-common
          mountPath: /mnt/etc/common
        - name: etc-glance
          mountPath: /mnt/etc/glance
        - name: bin-glance
          mountPath: /mnt/bin/glance
        - name: bin-init-controller
          mountPath: /mnt/bin/init-controller
        env:
        - name: WATCH_FILES
          value: '/mnt/bin/glance/bootstrap.sh,/mnt/bin/glance/dbsync.sh'
        - name: WATCH_INTERVAL
          value: '10'
      volumes:
      - name: etc-common
        configMap:
          name: etc-common
      - name: etc-glance
        configMap:
          name: etc-glance
      - name: bin-glance
        configMap:
          name: bin-glance
      - name: bin-init-controller
        configMap:
          name: bin-init-controller
