apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nova-api
  labels:
    chart: nova
spec:
  replicas: {{ .Values.nova.api.replicas }}
  template:
    metadata:
      labels:
        app: nova-api
    spec:
      nodeSelector:
        openstack-controller: ""
      containers:
      - name: nova-api
        # command: ["bash", "-c", "echo 'pre setup' && sleep 3600;"]
        command: [
          "/opt/nova/bin/nova-api",
          "--config-file", "/etc/nova/nova.conf",
        ]
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          privileged: true
        ports:
        - containerPort: 8774
        volumeMounts:
        - name: etc-nova
          mountPath: /etc/nova
      volumes:
      - name: etc-nova
        configMap:
          name: etc-nova
