{{- $nova := .Values.chart.nova }}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nova-scheduler
  labels:
    chart: nova
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nova-scheduler
      annotations:
        nova-configmap: {{ tuple "nova-configmap.yaml" . | include "funcs.hash" }}
    spec:
      hostNetwork: true
      serviceAccount: openstack
      nodeSelector:
        openstack-controller: ""
      containers:
        - name: nova-scheduler
          command: ["/mnt/nova/bin/nova.sh", "start_scheduler"]
          image: "{{ $nova.image.repository }}:{{ $nova.image.tag }}"
          imagePullPolicy: {{ $nova.image.pull_prolicy }}
          volumeMounts:
            - name: nova-bin
              mountPath: /mnt/nova/bin
            - name: nova-etc
              mountPath: /mnt/nova/etc
            - name: openstack-etc
              mountPath: /mnt/openstack/etc
      volumes:
        - name: nova-bin
          configMap:
            name: nova-bin
            defaultMode: 0755
        - name: nova-etc
          configMap:
            name: nova-etc
        - name: openstack-etc
          configMap:
            name: openstack-etc


---


apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nova-conductor
  labels:
    chart: nova
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nova-conductor
      annotations:
        nova-configmap: {{ tuple "nova-configmap.yaml" . | include "funcs.hash" }}
    spec:
      serviceAccount: openstack
      hostNetwork: true
      nodeSelector:
        openstack-controller: ""
      containers:
        - name: nova-conductor
          command: ["/mnt/nova/bin/nova.sh", "start_conductor"]
          image: "{{ $nova.image.repository }}:{{ $nova.image.tag }}"
          imagePullPolicy: {{ $nova.image.pull_prolicy }}
          volumeMounts:
            - name: nova-bin
              mountPath: /mnt/nova/bin
            - name: nova-etc
              mountPath: /mnt/nova/etc
            - name: openstack-etc
              mountPath: /mnt/openstack/etc
      volumes:
        - name: nova-bin
          configMap:
            name: nova-bin
            defaultMode: 0755
        - name: nova-etc
          configMap:
            name: nova-etc
        - name: openstack-etc
          configMap:
            name: openstack-etc
