apiVersion: v1
kind: ConfigMap
metadata:
  name: nova-etc
data:
  nova.conf: |+
{{ tuple "etc/_nova.conf.tpl" . | include "funcs.template" | indent 4 }}


---


apiVersion: v1
kind: ConfigMap
metadata:
  name: nova-bin
data:
  nova.sh: |+
{{ tuple "bin/_nova.sh.tpl" . | include "funcs.template" | indent 4 }}
