{{- $nova := .Values.chart.nova }}
{{- $openstack := .Values.openstack }}
{{- $image := index .Values.image_map $openstack.version "openstack" }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nova
  labels:
    chart: nova
spec:
  replicas: {{ $nova.api.replicas }}
  template:
    metadata:
      labels:
        app: nova
      annotations:
        nova-configmap: {{ tuple "nova-configmap.yaml" . | include "funcs.hash" }}
    spec:
      serviceAccount: openstack
      nodeSelector:
        openstack-controller: enable
        openstack-region: {{ .Values.openstack.region }}
      containers:
        - name: nova
          securityContext:
            privileged: true
          command: ["/mnt/nova/bin/nova.sh", "start_api"]
          image: {{ $image.repository }}
          imagePullPolicy: {{ $image.pull_policy }}
          ports:
            - containerPort: 8774
          readinessProbe:
            timeoutSeconds: {{ $nova.probes_timeout }}
            exec:
              command: ["/mnt/nova/bin/nova.sh", "readiness_api"]
          livenessProbe:
            initialDelaySeconds: {{ $nova.probes_delay }}
            timeoutSeconds: {{ $nova.probes_timeout }}
            exec:
              command: ["/mnt/nova/bin/nova.sh", "liveness_api"]
          volumeMounts:
            - name: nova-bin
              mountPath: /mnt/nova/bin
            - name: nova-bin
              mountPath: /sbin/iptables
              subPath: fake-iptables.sh
              readOnly: true
            - name: nova-bin
              mountPath: /sbin/iptables-restore
              subPath: fake-iptables.sh
              readOnly: true
            - name: nova-bin
              mountPath: /sbin/iptables-save
              subPath: fake-iptables.sh
              readOnly: true
            - name: nova-etc
              mountPath: /mnt/nova/etc
            - name: openstack-etc
              mountPath: /mnt/openstack/etc
      volumes:
        - name: nova-bin
          configMap:
            name: nova-bin
            defaultMode: 0755
        - name: nova-etc
          configMap:
            name: nova-etc
        - name: openstack-etc
          configMap:
            name: openstack-etc
