{{- $openstack := .Values.openstack }}
{{- $image := index .Values.image_map $openstack.version "openstack" }}
{{- $nova := .Values.chart.nova }}

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: placement
  labels:
    chart: nova
spec:
  replicas: {{ $nova.placement.replicas }}
  template:
    metadata:
      labels:
        app: placement
      annotations:
        nova-configmap: {{ tuple "nova-configmap.yaml" . | include "funcs.hash" }}
        placement-configmap: {{ tuple "placement-configmap.yaml" . | include "funcs.hash" }}
    spec:
      serviceAccount: openstack
      containers:
        - name: nginx
          command: ["/mnt/placement/bin/placement.sh", "start_nginx"]
          image: {{ $image.repository }}
          imagePullPolicy: {{ $image.pull_policy }}
          ports:
            - name: placement-api
              containerPort: 8778
          volumeMounts:
            - name: placement-bin
              mountPath: /mnt/placement/bin
            - name: placement-etc
              mountPath: /mnt/placement/etc
        - name: placement-api
          command: ["/mnt/placement/bin/placement.sh", "start_placement"]
          image: {{ $image.repository }}
          imagePullPolicy: {{ $image.pull_policy }}
          volumeMounts:
            - name: placement-bin
              mountPath: /mnt/placement/bin
            - name: placement-etc
              mountPath: /mnt/placement/etc
            - name: nova-etc
              mountPath: /mnt/nova/etc
            - name: openstack-etc
              mountPath: /mnt/openstack/etc
      volumes:
        - name: placement-bin
          configMap:
            name: placement-bin
            defaultMode: 0755
        - name: placement-etc
          configMap:
            name: placement-etc
        - name: nova-etc
          configMap:
            name: nova-etc
        - name: openstack-etc
          configMap:
            name: openstack-etc
