apiVersion: v1
kind: Service
metadata:
  name: nova-api
  labels:
    chart: nova
spec:
  type: ClusterIP
  ports:
  - port: 8774
    targetPort: 8774
    protocol: TCP
    name: nova-api
  selector:
    app: nova-api


---


apiVersion: v1
kind: Service
metadata:
  name: placement-api
  labels:
    chart: nova
spec:
  type: ClusterIP
  ports:
  - port: 8778
    targetPort: 8778
    protocol: TCP
    name: placement-api
  selector:
    app: placement-api
