apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: neutron-controller
  labels:
    chart: neutron
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      name: neutron-controller
      labels:
        chart: neutron
    spec:
      containers:
      - name: neutron-controller
        # command: ["bash", "-c", "echo 'pre setup' && sleep 3600;"]
        command: ["dumb-init", "--", "/usr/bin/python3", "/mnt/bin/init-controller/init.py"]
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: etc-common
          mountPath: /mnt/etc/common
        - name: etc-neutron
          mountPath: /mnt/etc/neutron
        - name: bin-neutron
          mountPath: /mnt/bin/neutron
        - name: bin-init-controller
          mountPath: /mnt/bin/init-controller
        env:
        - name: WATCH_FILES
          value: '/mnt/bin/neutron/bootstrap.sh,/mnt/bin/neutron/dbsync.sh'
        - name: WATCH_INTERVAL
          value: '10'
      volumes:
      - name: etc-common
        configMap:
          name: etc-common
      - name: etc-neutron
        configMap:
          name: etc-neutron
      - name: bin-neutron
        configMap:
          name: bin-neutron
      - name: bin-init-controller
        configMap:
          name: bin-init-controller
