apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: neutron
  labels:
    chart: neutron
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: neutron
    spec:
      containers:
      - name: neutron-server
        # command: ["bash", "-c", "echo 'pre setup' && sleep 3600;"]
        command: [
          "/opt/neutron/bin/neutron-server",
          "--config-file", "/etc/neutron/neutron.conf",
          "--config-file", "/etc/neutron/ml2_conf.ini",
        ]
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 9292
        volumeMounts:
        - name: etc-neutron
          mountPath: /etc/neutron
      volumes:
      - name: etc-neutron
        configMap:
          name: etc-neutron
