apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: neutron-linuxbridge-agent
  labels:
    chart: neutron
spec:
  template:
    metadata:
      labels:
        app: neutron-linuxbridge-agent
    spec:
      hostNetwork: true
      containers:
      - name: neutron-linuxbrige-agent
        command: ["bash", "-c", "echo 'pre setup' && sleep 3600;"]
        # command: ["bash", "-c", "python3 /mnt/bin/init-eventlet/init.py"]
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          privileged: true
        volumeMounts:
        - name: neutron-etc
          mountPath: /etc/neutron
        - name: neutron-plugins-ml2-etc
          mountPath: /etc/neutron/plugins/ml2
        - name: libmodules
          mountPath: /lib/modules
          readOnly: true
        - name: run
          mountPath: /run
      volumes:
      - name: neutron-etc
        configMap:
          name: neutron-etc
      - name: neutron-plugins-ml2-etc
        configMap:
          name: neutron-plugins-ml2-etc
      - name: libmodules
        hostPath:
          path: /lib/modules
      - name: run
        hostPath:
          path: /run
