apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: neutron-linuxbridge-agent
  labels:
    chart: neutron
spec:
  template:
    metadata:
      labels:
        app: neutron-linuxbridge-agent
    spec:
      hostNetwork: true
      containers:
      - name: neutron-linuxbrige-agent
        # command: ["bash", "-c", "echo 'pre setup' && sleep 3600;"]
        command: ["bash", "-c", "python3 /mnt/bin/init-eventlet/init.py"]
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          privileged: true
        volumeMounts:
        - name: etc-neutron
          mountPath: /mnt/etc/neutron
        - name: etc-common
          mountPath: /etc/resolv.conf
          subPath: resolv.conf
        - name: bin-neutron
          mountPath: /mnt/bin/neutron
        - name: bin-init-eventlet
          mountPath: /mnt/bin/init-eventlet
        - name: libmodules
          mountPath: /lib/modules
          readOnly: true
        - name: run
          mountPath: /run
        env:
        - name: START_CMD
          value: '/opt/neutron/bin/neutron-linuxbridge-agent --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini --config-file /etc/neutron/plugins/ml2/linuxbridge_agent.ini'
        - name: WATCH_FILES
          value: '/mnt/etc/neutron/neutron.conf,/mnt/etc/neutron/ml2_conf.ini,/mnt/etc/neutron/linuxbridge_agent.ini'
      volumes:
      - name: etc-neutron
        configMap:
          name: etc-neutron
      - name: etc-common
        configMap:
          name: etc-common
      - name: bin-neutron
        configMap:
          name: bin-neutron
      - name: bin-init-eventlet
        configMap:
          name: bin-init-eventlet
      - name: libmodules
        hostPath:
          path: /lib/modules
      - name: run
        hostPath:
          path: /run
