# Default values for nova.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: syunkitada/openstack-all
  tag: stable-ocata
  pullPolicy: IfNotPresent
