# Default values for nova.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: syunkitada/centos7-openstack-all
  tag: pike
  pullPolicy: IfNotPresent
