# Default values for openstack-common.

replicaCount: 1
image:
  repository: syunkitada/centos7-openstack-all
  tag: pike
  pullPolicy: Always

network:
  dns:
    kubernetes_domain: cluster.local
    # this must list the skydns server first, and in calico
    # this is consistently 10.96.0.10
    servers:
    - 10.96.0.10

openstack:
  debug: true
  region: RegionOne
  http_protocol: https
  ingress_suffix: .k8s.example.com
  ingress_vip: 172.16.100.132
  ingress_tls: tls-ingress
  memcached_servers: openstack-cache-memcache@domain_suffix:11211
  enable_services: [keystone, glance, nova, neutron]
  admin_password: adminpass
  projects: [service]
  user_map:
    service:
      user: openstack
      password: openstackpass
      domain: default
      project: service
      role: admin
  keystone:
    token: {}


ingress:
  keystone_public:
    name: keystone-public
    backend: keystone
    port: 5000
  keystone_admin:
    name: keystone-admin
    backend: keystone
    port: 35357
  glance:
    name: glance
    backend: glance
    port: 9292
  neutron:
    name: neutron
    backend: neutron
    port: 9696
  nova:
    name: nova
    backend: nova
    port: 8774
  placement:
    name: placement
    backend: placement
    port: 8778
  horizon:
    name: horizon
    backend: horizon
    port: 8000


mysql:
  root_pass: rootpass
  database_map:
    common:
      dbs: [keystone, glance, nova_api, nova_cell0, nova, neutron]
      host: openstack-mysql.default.svc.cluster.local
      port: 3306
      user: root
      password: rootpass


rabbitmq:
  connection_map:
    common:
      transport_url: rabbit://openstack:openstackpass@openstack-rabbitmq@domain_suffix:5672
      user: openstack
      password: openstackpass
      host: openstack-rabbitmq.default.svc.cluster.local
      port: 5672
      vhost: ''
