# Default values for openstack-common.

replicaCount: 1
image:
  repository: syunkitada/openstack-all
  tag: stable-ocata
  pullPolicy: IfNotPresent

network:
  dns:
    kubernetes_domain: cluster.local
    # this must list the skydns server first, and in calico
    # this is consistently 10.96.0.10
    servers:
    - 10.96.0.10

openstack:
  debug: true
  ingress_suffix: -ingress
  ingress_vip: 192.168.122.132
  memcached_servers: openstack-cache-memcache@domain_suffix:11211
  enable_services:
    - keystone
    - glance
    - nova
    - nova_api
    - neutron
  admin_password: adminpass
  projects: [service]
  user_map:
    service:
      user: openstack
      password: openstackpass
      domain: default
      project: service
      role: admin
  service_map:
    keystone:
      region: RegionOne
      public_url: http://keystone-public@ingress_suffix/v3/
      internal_url: http://keystone-public@ingress_suffix/v3/
      admin_url: http://keystone-admin@ingress_suffix/v3/
      auth_uri: http://keystone-public@ingress_suffix
      auth_url: http://keystone-admin@ingress_suffix
    glance:
      enable: true
      description: "OpenStack Image"
      type: image
      region: RegionOne
      public_url: http://glance-api@ingress_suffix
      internal_url: http://glance-api@ingress_suffix
      admin_url: http://glance-api@ingress_suffix
    neutron:
      enable: true
      description: "OpenStack Networking"
      type: network
      region: RegionOne
      public_url: http://neutron-server@ingress_suffix
      internal_url: http://neutron-server@ingress_suffix
      admin_url: http://neutron-server@ingress_suffix
    nova:
      enable: true
      description: "OpenStack Compute"
      type: compute
      region: RegionOne
      public_url: http://nova-api@ingress_suffix/v2.1
      internal_url: http://nova-api@ingress_suffix/v2.1
      admin_url: http://nova-api@ingress_suffix/v2.1
    placement:
      enable: true
      description: "Placement API"
      type: placement
      region: RegionOne
      public_url: http://placement-api@ingress_suffix
      internal_url: http://placement-api@ingress_suffix
      admin_url: http://placement-api@ingress_suffix

keystone:
  default:
    debug: true
  token:
    provider: uuid


ingress:
  - name: keystone-public
    backend: keystone
    port: 5000
  - name: keystone-admin
    backend: keystone
    port: 35357
  - name: glance-api
    backend: glance-api
    port: 9292
  - name: neutron-server
    backend: neutron-server
    port: 9696
  - name: nova-api
    backend: nova-api
    port: 8774
  - name: placement-api
    backend: placement-api
    port: 8778


mysql:
  root_pass: rootpass
  database_map:
    common:
      dbs: [keystone, glance, nova_api, nova_cell0, nova, neutron]
      # host: openstack-db-mariadb.default.svc.cluster.local
      host: openstack-mysql@domain_suffix
      port: 3306
      user: root
      password: rootpass


rabbitmq:
  connection_map:
    common:
      transport_url: rabbit://openstack:openstackpass@openstack-rabbitmq@domain_suffix:5672
      user: openstack
      password: openstackpass
      host: openstack-rpc-rabbitmq@domain_suffix
      port: 5672
      vhost: ''
