# Default values for openstack-common.

replicaCount: 1
image:
  repository: syunkitada/openstack-all
  tag: stable-ocata
  pullPolicy: IfNotPresent

network:
  dns:
    kubernetes_domain: cluster.local
    # this must list the skydns server first, and in calico
    # this is consistently 10.96.0.10
    servers:
    - 10.96.0.10

openstack:
  memcached_servers: openstack-cache-memcache.@domain_suffix:11211
  enable_services:
    - keystone
    - glance
    - nova
    - nova_api
    - neutron
  rpc_map:
    common:
      user: openstack
      password: openstackpass
      host: openstack-rpc-rabbitmq.@domain_suffix
      port: 5672
      vhost: ''
  admin_password: adminpass
  projects: [service]
  database_map:
    common:
      dbs: [keystone, glance, nova_api, nova_cell0, nova, neutron]
      # host: openstack-db-mariadb.default.svc.cluster.local
      host: openstack-mysql.@domain_suffix
      port: 3306
      user: root
      password: rootpass
  user_map:
    service:
      user: openstack
      password: openstackpass
      domain: default
      project: service
      role: admin
  service_map:
    keystone:
      region: RegionOne
      public_url: http://keystone.@domain_suffix:5000/v3/
      internal_url: http://keystone.@domain_suffix:5000/v3/
      admin_url: http://keystone.@domain_suffix:35357/v3/
      auth_uri: http://keystone.@domain_suffix:5000
      auth_url: http://keystone.@domain_suffix:35357
    glance:
      enable: true
      description: "OpenStack Image"
      type: image
      region: RegionOne
      public_url: http://glance-api.@domain_suffix:9292
      internal_url: http://glance-api.@domain_suffix:9292
      admin_url: http://glance-api.@domain_suffix:9292
    neutron:
      enable: true
      description: "OpenStack Networking"
      type: network
      region: RegionOne
      public_url: http://neutron-server.@domain_suffix:9696
      internal_url: http://neutron-server.@domain_suffix:9696
      admin_url: http://neutron-server.@domain_suffix:9696
    nova:
      enable: true
      description: "OpenStack Compute"
      type: compute
      region: RegionOne
      public_url: http://nova-api.@domain_suffix:8774/v2.1
      internal_url: http://nova-api.@domain_suffix:8774/v2.1
      admin_url: http://nova-api.@domain_suffix:8774/v2.1
    placement:
      enable: true
      description: "Placement API"
      type: placement
      region: RegionOne
      public_url: http://placement-api.@domain_suffix:8778
      internal_url: http://placement-api.@domain_suffix:8778
      admin_url: http://placement-api.@domain_suffix:8778

keystone:
  default:
    debug: true
  token:
    provider: uuid


mysql:
  root_pass: rootpass
  database_map:
    common:
      dbs: [keystone, glance, nova_api, nova_cell0, nova, neutron]
      # host: openstack-db-mariadb.default.svc.cluster.local
      host: openstack-mysql.@domain_suffix
      port: 3306
      user: root
      password: rootpass
