apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.serviceType }}
  ports:
  - name: mariadb
    port: 3306
    targetPort: mariadb
  selector:
    app: "{{ .Release.Name }}"
