chart:
  elasticsearch:
    version: v2.4.1
    image:
      repository: gcr.io/google-containers/elasticsearch
      tag: v2.4.1-3
      pullPolicy: Always
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
      requests:
        cpu: 100m
    es_heap_size: 256m

  kibana:
    image:
      repository: gcr.io/google_containers/kibana
      tag: v4.6.1-1
      pullPolicy: Always
    resources:
      limits:
        cpu: 1000m
      requests:
        cpu: 100m

  fluentd:
    image:
      repository: gcr.io/google_containers/fluentd-elasticsearch
      tag: 1.24
      pullPolicy: Always
    resources:
      limits:
        cpu: 500m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 128Mi
