{{- $http_protocol := .Values.openstack.http_protocol }}
{{- $ingress_suffix := .Values.openstack.ingress_suffix }}
{{- $ingress_vip := .Values.openstack.ingress_vip }}
{{- $ingress_tls := .Values.openstack.ingress_tls }}
{{- range $key, $ingress := .Values.ingress }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $ingress.name }}
  annotations:
    ingress.kubernetes.io/proxy-body-size: 1g
spec:
  {{- if eq $http_protocol "https" }}
  tls:
    - secretName: {{ $ingress_tls }}
      hosts:
        - {{ $ingress.name }}{{ $ingress_suffix }}
  {{- end }}
  rules:
    - host: {{ $ingress.name }}{{ $ingress_suffix }}
      http:
        paths:
          - backend:
              serviceName: {{ $ingress.backend }}
              servicePort: {{ $ingress.port }}


---
{{- end }}
