{{- $domain_suffix := print .Release.Namespace ".svc.cluster.local" }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-neutron
data:
  neutron.conf: |+
{{ tuple "etc/neutron/_neutron.conf.tpl" . | include "funcs.template" | indent 4 | replace "@domain_suffix" $domain_suffix }}
  api-paste.ini: |+
{{ tuple "etc/neutron/_api-paste.ini.tpl" . | include "funcs.template" | indent 4 }}
  dhcp_agent.ini: |+
{{ tuple "etc/neutron/_dhcp_agent.ini.tpl" . | include "funcs.template" | indent 4 }}
  metadata_agent.ini: |+
{{ tuple "etc/neutron/_metadata_agent.ini.tpl" . | include "funcs.template" | indent 4 }}
  policy.json: |+
{{ tuple "etc/neutron/_policy.json.tpl" . | include "funcs.template" | indent 4 }}
  rootwrap.conf: |+
{{ tuple "etc/neutron/_rootwrap.conf.tpl" . | include "funcs.template" | indent 4 }}
  ml2_conf.ini: |+
{{ tuple "etc/neutron/_ml2_conf.ini.tpl" . | include "funcs.template" | indent 4 }}
  linuxbridge_agent.ini: |+
{{ tuple "etc/neutron/_linuxbridge_agent.ini.tpl" . | include "funcs.template" | indent 4 }}


---


apiVersion: v1
kind: ConfigMap
metadata:
  name: bin-neutron
data:
  bootstrap.sh: |+
{{ tuple "bin/neutron/_bootstrap.sh.tpl" . | include "funcs.template" | indent 4 | replace "@domain_suffix" $domain_suffix }}
