{{- $domain_suffix := print .Release.Namespace ".svc.cluster.local" }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-nova
data:
  nova.conf: |+
{{ tuple "etc/nova/_nova.conf.tpl" . | include "funcs.template" | indent 4 | replace "@domain_suffix" $domain_suffix }}
  api-paste.ini: |+
{{ tuple "etc/nova/_api-paste.ini.tpl" . | include "funcs.template" | indent 4 }}
  rootwrap.conf: |+
{{ tuple "etc/nova/_rootwrap.conf.tpl" . | include "funcs.template" | indent 4 }}


---


apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-nova-placement-nginx-conf
data:
  nova-placement-nginx.conf: |+
{{ tuple "etc/nova/_nova-placement-nginx.conf.tpl" . | include "funcs.template" | indent 4 }}


---


apiVersion: v1
kind: ConfigMap
metadata:
  name: bin-nova
data:
  syncdb.sh: |+
{{ tuple "bin/nova/_syncdb.sh.tpl" . | include "funcs.template" | indent 4 | replace "@domain_suffix" $domain_suffix }}
  start-compute.sh: |+
{{ tuple "bin/nova/_start-compute.sh.tpl" . | include "funcs.template" | indent 4 | replace "@domain_suffix" $domain_suffix }}
