apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: openstack-deploy-manager
  labels:
    chart: openstack
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      name: openstack-deploy-manager
      labels:
        chart: openstack
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirst
      serviceAccount: openstack
      nodeSelector:
        openstack-controller: ""
      containers:
        - name: openstack-deploy-manager
          # command: ["bash", "-c", "echo 'pre setup' && sleep 3600;"]
          command: ["/mnt/openstack/bin/deploy-manager.py"]
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: openstack-bin
              mountPath: /mnt/openstack/bin
            - name: openstack-etc
              mountPath: /mnt/openstack/etc
          env:
            - name: WATCH_INTERVAL
              value: '20'
      volumes:
        - name: openstack-bin
          configMap:
            name: openstack-bin
            defaultMode: 0755
        - name: openstack-etc
          configMap:
            name: openstack-etc
