{{- $domain_suffix := print .Release.Namespace ".svc.cluster.local" }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-openstack
data:
  adminrc: |+
{{ tuple "etc/openstack/_adminrc.tpl" . | include "funcs.template" | indent 4 | replace "@domain_suffix" $domain_suffix }}
  resolv.conf: |+
{{ tuple "etc/openstack/_resolv.conf.tpl" . | include "funcs.template" | indent 4 }}


---


apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-resolv-conf
data:
  resolv.conf: |+
{{ tuple "etc/openstack/_resolv.conf.tpl" . | include "funcs.template" | indent 4 }}


---


apiVersion: v1
kind: ConfigMap
metadata:
  name: root-home
data:
  adminrc: |+
{{ tuple "root/_adminrc.tpl" . | include "funcs.template" | indent 4 | replace "@domain_suffix" $domain_suffix }}


---


apiVersion: v1
kind: ConfigMap
metadata:
  name: bin-openstack
data:
  util.py: |+
{{ tuple "bin/openstack/_util.py.tpl" . | include "funcs.template" | indent 4 | replace "@domain_suffix" $domain_suffix }}
  start-bootstrap.py: |+
{{ tuple "bin/openstack/_start-bootstrap.py.tpl" . | include "funcs.template" | indent 4 | replace "@domain_suffix" $domain_suffix }}
  bootstrap-01-mysql.sh: |+
{{ tuple "bin/openstack/bootstrap/_mysql.sh.tpl" . | include "funcs.template" | indent 4 | replace "@domain_suffix" $domain_suffix }}
  bootstrap-02-memcached.sh: |+
{{ tuple "bin/openstack/bootstrap/_memcached.sh.tpl" . | include "funcs.template" | indent 4 | replace "@domain_suffix" $domain_suffix }}
  bootstrap-03-rabbitmq.sh: |+
{{ tuple "bin/openstack/bootstrap/_rabbitmq.sh.tpl" . | include "funcs.template" | indent 4 | replace "@domain_suffix" $domain_suffix }}
  bootstrap-10-keystone.sh: |+
{{ tuple "bin/openstack/bootstrap/_keystone.sh.tpl" . | include "funcs.template" | indent 4 | replace "@domain_suffix" $domain_suffix }}
