apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: openstack-controller
  labels:
    chart: openstack
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      name: openstack-controller
      labels:
        chart: openstack
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirst
      serviceAccount: openstack
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
        - key: CriticalAddonsOnly
          operator: Exists
      nodeSelector:
        node-role.kubernetes.io/master: ""
      containers:
        - name: openstack-controller
          command: ["bash", "-c", "echo 'pre setup' && sleep 3600;"]
          # command: ["/mnt/bin/openstack/start-bootstrap.py"]
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: openstack-bin
              mountPath: /mnt/openstack/bin
            - name: openstack-etc
              mountPath: /mnt/openstack/etc
          env:
            - name: WATCH_INTERVAL
              value: '10'
      volumes:
        - name: openstack-bin
          configMap:
            name: openstack-bin
            defaultMode: 0755
        - name: openstack-etc
          configMap:
            name: openstack-etc
