{{- $domain_suffix := print .Release.Namespace ".svc.cluster.local" }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-openstack
data:
  adminrc: |+
{{ tuple "etc/openstack/_adminrc.tpl" . | include "funcs.template" | indent 4 | replace "@domain_suffix" $domain_suffix }}
  resolv.conf: |+
{{ tuple "etc/openstack/_resolv.conf.tpl" . | include "funcs.template" | indent 4 }}


---


apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-resolv-conf
data:
  resolv.conf: |+
{{ tuple "etc/openstack/_resolv.conf.tpl" . | include "funcs.template" | indent 4 }}


---


apiVersion: v1
kind: ConfigMap
metadata:
  name: root-home
data:
  adminrc: |+
{{ tuple "root/_adminrc.tpl" . | include "funcs.template" | indent 4 | replace "@domain_suffix" $domain_suffix }}
