apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: openstack-controller
  labels:
    chart: openstack
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      name: openstack-controller
      labels:
        chart: openstack
    spec:
      hostNetwork: true
      serviceAccount: openstack
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
        - key: CriticalAddonsOnly
          operator: Exists
      nodeSelector:
        node-role.kubernetes.io/master: ""
      containers:
        - name: openstack-controller
          command: ["bash", "-c", "echo 'pre setup' && sleep 3600;"]
          # command: ["/mnt/bin/openstack/start-bootstrap.py"]
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: opt-kubernetes
              mountPath: /opt/kubernetes
            - name: opt-openstack-helm
              mountPath: /opt/openstack-helm
            - name: bin-openstack
              mountPath: /mnt/bin/openstack
            - name: etc-resolv-conf
              mountPath: /etc/resolv.conf
              subPath: resolv.conf
            - name: etc-openstack
              mountPath: /etc/openstack
            - name: etc-keystone
              mountPath: /etc/keystone
            - name: etc-glance
              mountPath: /etc/glance
            - name: etc-neutron
              mountPath: /etc/neutron
            - name: etc-nova
              mountPath: /etc/nova
          env:
            - name: WATCH_INTERVAL
              value: '10'
      volumes:
        - name: opt-kubernetes
          hostPath:
            path: /opt/kubernetes
        - name: opt-openstack-helm
          hostPath:
            path: /opt/openstack-helm
        - name: bin-openstack
          configMap:
            name: bin-openstack
            defaultMode: 0755
        - name: etc-resolv-conf
          configMap:
            name: etc-resolv-conf
        - name: etc-openstack
          configMap:
            name: etc-openstack
        - name: etc-keystone
          configMap:
            name: etc-keystone
        - name: etc-glance
          configMap:
            name: etc-glance
        - name: etc-neutron
          configMap:
            name: etc-neutron
        - name: etc-nova
          configMap:
            name: etc-nova
