apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: horizon
  labels:
    chart: horizon
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: horizon
    spec:
      containers:
      - name: nginx
        command: ["/bin/bash", "-c", "nginx -g 'daemon off;'"]
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: horizon
            containerPort: 80
        volumeMounts:
          - name: etc-horizon-nginx-conf
            mountPath: /etc/nginx/conf.d
      - name: horizon
        # command: ["bash", "-c", "echo 'pre setup' && sleep 3600;"]
        command: ["/mnt/bin/horizon/start.sh"]
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: etc-horizon
          mountPath: /etc/horizon
        - name: bin-horizon
          mountPath: /mnt/bin/horizon
      volumes:
      - name: bin-horizon
        configMap:
          name: bin-horizon
          defaultMode: 0755
      - name: etc-horizon
        configMap:
          name: etc-horizon
      - name: etc-horizon-nginx-conf
        configMap:
          name: etc-horizon-nginx-conf
