apiVersion: v1
kind: Service
metadata:
  name: horizon
  labels:
    chart: horizon
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: horizon
  selector:
    app: horizon
